### ISSUE TITLE
Data stewardship

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-cli#65]
Data stewardship is about keeping your data hosted on the Swarm network. For more detailed background see [this issue](https://github.com/ethersphere/bee/issues/1508).

In the context of the `swarm-cli` tool this would mean:
- [x] be able to pin content when uploading
- [x] pin in retrospect (https://github.com/ethersphere/swarm-cli/issues/59)
- [x] pin feed update and upload (https://github.com/ethersphere/swarm-cli/issues/58)
- [x] get the list of current pins (https://github.com/ethersphere/bee/issues/1302)
- [ ] reupload to network (https://github.com/ethersphere/bee/issues/1051)
- [ ] reupload pinned chunks (https://github.com/ethersphere/bee/issues/852)

**Comment by agazso** [comment]
I think the only missing thing from this list is to reupload pinned chunk. I imagine that it could work by having an option to the `pinning reupload` command to upload all the pinned content. For example:

`swarm-cli pinning reupload -a`

vs. 

`swarm-cli pinning reupload <address>`

@Cafe137 What do you think?

**Comment by Cafe137** [comment]
@agazso Good idea, I am working on it.
